# -*- conf -*-

[main]
include=/home/aksel/.config/foot/themes/solarized-dark.ini

shell=/usr/bin/bash
pad=5x5

# font=JetBrainsMono Nerd Font:size=14
# font=IosevkaTerm Nerd Font:size=12
font=IosevkaTerm Nerd Font:size=10
# font=Inconsolata Nerd Font:size=13
# font=FiraCode Nerd Font:size=12
# font=Hack Nerd Font:size=10

# Theme

[cursor]
style=underline
blink=yes

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=1.0
